### ISSUE TITLE
Readme typos

### ISSUE THREAD

**Issue by pixeleffect** [paypal/buttonmanager-sdk-php#22]
### Issue description

README.md has two typos under the "Using the SDK" section in the "For Example" code.

```php
    use PayPal\PayPalAPI\ButtonManagerService;
```
should be
```php
    use PayPal\Service\ButtonManagerService;
```

and

```php
    if($strtoupper($buttonSearchResponse->Ack) == 'SUCCESS') {
```
should be
```php
    if(strtoupper($buttonSearchResponse->Ack) == 'SUCCESS') {
```

**Comment by xiaoleih41** [comment]
Thank you, I have submitted a pull request on these two issues.  https://github.com/paypal/buttonmanager-sdk-php/pull/23
